openapi: 3.0.0
info:
  version: '1.0.0'
  title: File API

paths:
  /status:
    get:
      summary: Status
      description: Get Status.
      responses:
        '200':
          description: It's a response.
  /file/:
    get:
      summary: Get File
      description: Get File Response.
      responses:
        '200':
          description: It's a response.

security:
  - basicAuth: []
